name: clipboard_watcher
description: This plugin allows Flutter apps to watch clipboard changes.
version: 0.2.0
homepage: https://github.com/leanflutter/clipboard_watcher

platforms:
  linux:
  macos:
  windows:
  ios:
  android:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  dependency_validator: ^3.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: ClipboardWatcherPlugin
      macos:
        pluginClass: ClipboardWatcherPlugin
      windows:
        pluginClass: ClipboardWatcherPlugin
      ios:
        pluginClass: ClipboardWatcherPlugin
      android:
        pluginClass: ClipboardWatcherPlugin
        package: clipboard.watcher
